spring.application.name=SkillSync
#spring.data.mongodb.uri=mongodb+srv://smart-wallet:admin@smart-wallet.j2jkswq.mongodb.net/?appName=skill-sync
# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://smart-wallet.j2jkswq.mongodb.net/skill-sync
spring.data.mongodb.username=smart-wallet
spring.data.mongodb.password=admin
spring.data.mongodb.database=skill-sync